model_path: "C:\\Users\\zhang\\juypter_notebook_workplace\\model"
payload_path: "C:\\Users\\zhang\\workspace\\packvirus\\src\\virus\\rev.bs64"
key: "1100110011001100"
algorithm: "aes"
# 校验和

dependencies:
  python: "3.7"
  tensorflow: "2"