model_path: "C:\\Users\\zhang\\workspace\\packvirus\\src\\model\\mnist_2"
payload_path: "C:\\Users\\zhang\\workspace\\packvirus\\src\\virus\\rev.bs64"
key: "0100010001000100"
algorithm: "aes"
# 校验和

dependencies:
  python: "3.7"
  tensorflow: "2"